version: '3.1'

services:
  #Billin app backend service
  server-eureka:
    image: server-eureka:v1
    container_name: server-eureka
    build:
      context: ./
      args:
        - JAR_FILE=EdutainmentEurekaServer-0.0.1-SNAPSHOT.jar
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "650M"
        reservations:
          cpus: "1.5"
          memory: "150M"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    networks:
      - edutainment-private-network

networks:
  edutainment-private-network:
    driver: edutainment-private-network
    external: true