version: '3.1'

services:
  #Billin app backend service
  eureka-server:
    container_name: eureka-server
    build:
      context: ./
      args:
        - JAR_FILE=./target/eureka-server.jar
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "650M"
        reservations:
          cpus: "1.5"
          memory: "150M"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    ports:
      - "8761:8761"
    networks:
      - edutainment-network

networks:
  edutainment-network:
    driver: edutainment-network
    external: true

# End