version: '3.1'

services:
  #Billin app backend service
  api-gateway-server:
    build:
      context: ./
      args:
        - JAR_FILE=api-gateway-server.jar
    container_name: api-gateway-server
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "650M"
        reservations:
          cpus: "0.70"
          memory: "150M"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    ports:
      - "8761:8761"
networks:
  micro-service-cloud:
    driver: bridge
    ipam:
      driver: defaul
      config:
        - subnet: 172.16.232.0/24
          gateway: 172.16.232.1

# End