spring.application.name = edutainment-eureka-server
server.port=8761
#   EUREKA CONFIGURATION, O THIS SECTION WE NEED CONFIGURE THE SERVER EUREKA.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
