spring.application.name=eureka-server
server.port=8761
#   EUREKA CONFIGURATION, O THIS SECTION WE NEED CONFIGURE THE SERVER EUREKA.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=eureka-server
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/